
package com.topsun.posclient.common.webservice.test;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-07-12T14:38:38.075-07:00
 * Generated source version: 2.7.4
 * 
 */
public final class IRMSServices_BasicHttpBindingIRMSServices_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Services");

    private IRMSServices_BasicHttpBindingIRMSServices_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Services.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Services ss = new Services(wsdlURL, SERVICE_NAME);
        IRMSServices port = ss.getBasicHttpBindingIRMSServices();  
        
        {
        System.out.println("Invoking getUserInfo...");
        
        GetUserInfo getUserInfo = new GetUserInfo();
        
        GetUserInfoResult _getUserInfo__return = port.getUserInfo(getUserInfo);
        System.out.println("getUserInfo.result=" + _getUserInfo__return);


        }
        {
        System.out.println("Invoking savePartSales...");
        PartSalesData _savePartSales_savePartSalesReq = null;
        SavePartSalesResult _savePartSales__return = port.savePartSales(_savePartSales_savePartSalesReq);
        System.out.println("savePartSales.result=" + _savePartSales__return);


        }

        System.exit(0);
    }

}
