package com.topsun.posclient.finance.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-25T14:08:35.275-07:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://service.pos.webservice.topsunit.com/", name = "IFinanceService")
public interface IFinanceService {

    @WebResult(name = "syncData", targetNamespace = "")
    @RequestWrapper(localName = "saveStorePay", targetNamespace = "http://service.pos.webservice.topsunit.com/", className = "webservice.SaveStorePay")
    @WebMethod
    @ResponseWrapper(localName = "saveStorePayResponse", targetNamespace = "http://service.pos.webservice.topsunit.com/", className = "webservice.SaveStorePayResponse")
    public String saveStorePay(
        @WebParam(name = "payRecordDTO", targetNamespace = "")PayRecordDTO payRecordDTO
    );
}
