package com.topsun.posclient.common.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-30T18:02:00.365-07:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://service.pos.webservice.topsunit.com/", name = "IPosWebService")
public interface IPosWebService {

    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public boolean saveReceive(
        @WebParam(name = "receiveDTO", targetNamespace = "")String receiveDTO
    );

    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public boolean savePayment(
        @WebParam(name = "paymentDTO", targetNamespace = "")String paymentDTO
    );

    @WebResult(name = "syncData", targetNamespace = "")
    @WebMethod
    public String syncData(
        @WebParam(name = "type", targetNamespace = "")String type
    );

    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public boolean savePartSales(
        @WebParam(name = "partSalesDTO", targetNamespace = "")String partSalesDTO
    );

    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public boolean saveStorePay(
        @WebParam(name = "payRecordDTO", targetNamespace = "")String payRecordDTO
    );
}
