package com.topsun.posclient.common.webservice;

import javax.jws.WebParam;
import javax.jws.WebService;

import com.topsun.posclient.datamodel.dto.webservice.GetUserInfoResult;
import com.topsun.posclient.datamodel.dto.webservice.UserInfoReq;

/**
 * This class was generated by Apache CXF 2.7.4 2013-07-10T17:52:46.689-07:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://www.topsunit.com/rms", name = "IRMSServices")
public interface IRMSServices {

	public GetUserInfoResult getUserInfo(
			@WebParam(name = "getUserInfoReq", targetNamespace = "http://www.topsunit.com/rms") UserInfoReq userInfoReq);

	// public SavePartSalesResult savePartSales(
	// @WebParam(name = "savePartSalesReq", targetNamespace =
	// "http://www.topsunit.com/rms")
	// PartSalesData savePartSalesReq
	// );
}
